#! /usr/bin/env python

# Copyright (c) 2010-2011, Lawrence Livermore National Security, LLC
# Produced at Lawrence Livermore National Laboratory
# LLNL-CODE-462894
# All rights reserved.
#
# This file is part of MixDown. Please read the COPYRIGHT file
# for Our Notice and the LICENSE file for the GNU Lesser General Public
# License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License (as published by
# the Free Software Foundation) version 3 dated June 2007.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms and
# conditions of the GNU Lesser General Public License for more details.
#
#  You should have recieved a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import sys, unittest
import test_autoTools, test_cmake, test_cvs, test_git, test_hg, test_steps, test_svn, test_project, test_target
import test_MixDownLong, test_MixDownShort, test_utilityFunctions

if not ".." in sys.path:
    sys.path.append("..")

from md import logger

def main():
    longTests = False
    suite = unittest.TestSuite()

    suite.addTest(test_autoTools.suite())
    suite.addTest(test_cmake.suite())
    #suite.addTest(test_cvs.suite())
    suite.addTest(test_git.suite())
    suite.addTest(test_hg.suite())
    suite.addTest(test_steps.suite())
    suite.addTest(test_svn.suite())
    suite.addTest(test_project.suite())
    suite.addTest(test_target.suite())
    suite.addTest(test_MixDownShort.suite())
    suite.addTest(test_utilityFunctions.suite())

    if "--long" in sys.argv:
        suite.addTest(test_MixDownLong.suite())
        longTests = True

    unittest.TextTestRunner(verbosity=2).run(suite)

    if not longTests:
        print "\nNote: Long tests not run to enable add '--long' to command line"

if __name__ == "__main__":
    logger.setLogger("Console")
    main()
