#! /usr/bin/env python

# Copyright (c) 2010, Lawrence Livermore National Security, LLC
# Produced at Lawrence Livermore National Laboratory
# LLNL-CODE-462894
# All rights reserved.
#
# This file is part of MixDown. Please read the COPYRIGHT file
# for Our Notice and the LICENSE file for the GNU Lesser General Public
# License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License (as published by
# the Free Software Foundation) version 3 dated June 2007.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms and
# conditions of the GNU Lesser General Public License for more details.
#
#  You should have recieved a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import os, sys, tarfile, time, urllib

from md import mdCommands, mdImporter, mdOptions, mdProject, mdDefines, utilityFunctions, mdLogger

#--------------------------------Main---------------------------------
def main():
    mdLogger.SetLogger("console")
    mdLogger.Logger().writeMessage("MixDown - A tool to simplify building\n")
    try:
        succeeded = True
        partialImport = False
        options = mdOptions.Options()
        targetsToImport = options.processCommandline(sys.argv)

        if (not options.importer or not targetsToImport) and not\
           options.cleanTargets and options.projectFile == "":
            options.printUsageAndExit("MixDown's mode could not be determined")
        timeStarted = time.time()

        if options.importer:
            project, partialImport = mdImporter.importTargets(options, targetsToImport)
            if project == None or partialImport:
                succeeded = False
        else:
            if options.cleanMixDown:
                cleanMixDown(options)
            project = setup(options)
            if project == None:
                succeeded = False
            else:
                for target in reversed(project.targets):
                    if options.cleanTargets:
                        cleanStep = target.findBuildStep("clean")
                        succeeded = mdCommands.buildStepActor(target, cleanStep, options)
                    else:
                        for buildStep in target.buildSteps:
                            if buildStep.name == "clean" or buildStep.command == "":
                                continue
                            succeeded = mdCommands.buildStepActor(target, buildStep, options)
                            if not succeeded:
                                break
                    if not succeeded:
                        break

        timeFinished = time.time()
        timeElapsed = timeFinished - timeStarted

        message = "Project "
        if project != None:
            message += project.name

        if not succeeded:
            message += " failed."
        else:
            message += " succeeded."
            if options.importer:
                mdLogger.Logger().writeMessage("\nProject " + project.name + " has been imported to file " + project.path)
            elif options.cleanTargets:
                mdLogger.Logger().writeMessage("\n" + project.name + " has been cleaned in " + os.path.abspath(options.buildDir))
            else:
                mdLogger.Logger().writeMessage("\n" + project.name + " has been built in " + os.path.abspath(options.buildDir))
                mdLogger.Logger().writeMessage(project.name + " has been installed to " + os.path.abspath(options.getDefine(mdDefines.mdPrefix[0])))
        message = "\nTotal time " + mdLogger.secondsToHMS(timeElapsed) + "\n" + message
        mdLogger.Logger().writeMessage(message)
        if partialImport:
            mdLogger.Logger().writeError("\nProject partially imported.  Please refer to comments in created MixDown project file to determine reason.")
    finally:
        mdLogger.Logger().close()
    if succeeded:
        sys.exit()
    else:
        sys.exit(1)

#--------------------------------Setup---------------------------------
def setup(options):
    mdLogger.SetLogger(options.logger, options.logDir)
    if options.verbose:
        mdLogger.Logger().writeMessage(str(options))
        if not options.prefixDefined and not options.cleanTargets:
            mdLogger.Logger().writeMessage("No prefix defined, defaulting to '" + options.getDefine(mdDefines.mdPrefix[0]) + "'")

    project = mdProject.Project(options.projectFile)
    if not project.read():
        return None
    if not project.addSkipStepFromOptions(options):
        return None

    if not project.examine(options):
        return None
    if not project.validate(options):
        return None

    if options.cleanTargets:
        for currTarget in project.targets:
            currTarget.path = currTarget.determineOutputPath(options)
    else:
        cleaningOutputReported = False
        for currTarget in project.targets:
            if currTarget.outputPath != "" and os.path.exists(currTarget.outputPath):
                if cleaningOutputReported:
                    mdLogger.Logger().writeMessage("Cleaning MixDown and Target output directories...")
                    cleaningOutputReported = True
                utilityFunctions.removeDir(currTarget.outputPath)

        prefixDefine = options.getDefine(mdDefines.mdPrefix[0])
        if prefixDefine != "":
            #TODO: only add lib64 if on 64bit machines
            libraryPaths = os.path.join(prefixDefine, "lib64") + ":" + os.path.join(prefixDefine, "lib")
            if os.environ.has_key("LD_LIBRARY_PATH"):
                originalLibraryPath = str.strip(os.environ["LD_LIBRARY_PATH"])
                if originalLibraryPath != "":
                    libraryPaths += ":" + originalLibraryPath
            os.environ["LD_LIBRARY_PATH"] = libraryPaths

    #Add MixDown's directory to path so mdSteps can be found
    print os.path.dirname(sys.argv[0])
    sys.path.append(os.path.dirname(sys.argv[0]))

    return project

def cleanMixDown(options):
    try:
        mdLogger.Logger().writeMessage("Cleaning MixDown directories...")
        utilityFunctions.removeDir(options.buildDir)
        utilityFunctions.removeDir(options.downloadDir)
        utilityFunctions.removeDir(options.logDir)
    except IOError, e:
        mdLogger.Logger().writeError(e, exitProgram=True)

#----------------------------------------------------------------------

if __name__ == "__main__":
    main()
