#! /usr/bin/env python

# Copyright (c) 2010, Lawrence Livermore National Security, LLC
# Produced at Lawrence Livermore National Laboratory
# LLNL-CODE-462894
# All rights reserved.
#
# This file is part of MixDown. Please read the COPYRIGHT file
# for Our Notice and the LICENSE file for the GNU Lesser General Public
# License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License (as published by
# the Free Software Foundation) version 3 dated June 2007.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms and
# conditions of the GNU Lesser General Public License for more details.
#
#  You should have recieved a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import os, sys, tarfile, time, urllib
import mdCommands, mdImporter, mdOptions, mdProject, mdStrings, utilityFunctions

from mdLogger import *

#--------------------------------Main---------------------------------
def main():
    SetLogger("console")
    Logger().writeMessage("MixDown - A tool to simplify building\n")
    try:
        options = mdOptions.Options()
        targetsToImport = options.processCommandline(sys.argv)

        timeStarted = time.time()

        if options.importer:
            project = mdImporter.importTargets(options, targetsToImport)
            if project != None:
                succeeded = True
            else:
                suceeded = False
        else:
            if options.cleanMixDown:
                cleanMixDown(options)
            project = setup(options)
            if project != None:
                for target in reversed(project.targets):
                    if options.cleanTargets:
                        succeeded = mdCommands.buildStepActor("clean", target, options)
                    else:
                        for step in mdCommands.getBuildStepList():
                            if step == "clean":
                                continue
                            succeeded = mdCommands.buildStepActor(step, target, options)
                            if not succeeded:
                                break
                    if not succeeded:
                        break

        timeFinished = time.time()
        timeElapsed = timeFinished - timeStarted
        if project == None:
            if options.importer:
                message = "Importing failed."
            else:
                message = "Project failed."
        else:
            if options.importer:
                message = "Importing project " + project.name
            else:
                message = "Project " + project.name
            if succeeded:
                message += " succeeded."
                if not options.importer:
                    if options.cleanTargets:
                        Logger().writeMessage("\n" + project.name + " has been cleaned in " + os.path.abspath(options.buildDir) + "\n")
                    else:
                        Logger().writeMessage("\n" + project.name + " has been built in " + os.path.abspath(options.buildDir))
                        Logger().writeMessage(project.name + " has been installed to " + os.path.abspath(options.getDefine(mdStrings.mdDefinePrefix)) + "\n")
            else:
                message += " failed."
        message = "Total time " + secondsToHMS(timeElapsed) + "\n" + message + "\n"
        Logger().writeMessage(message)
    finally:
        Logger().close()
    sys.exit()

#--------------------------------Setup---------------------------------
def setup(options):
    SetLogger(options.logger, options.logDir)
    if options.verbose:
        Logger().writeMessage(str(options))
        if not options.prefixDefined and not options.cleanTargets:
            Logger().writeMessage("No prefix defined, defaulting to '" + options.getDefine(mdStrings.mdDefinePrefix) + "'")

    project = mdProject.Project(options.projectFile)
    if not project.read():
        return None

    if not project.examine(options):
        return None
    if not project.validate(options):
        return None

    if options.cleanTargets:
        for currTarget in project.targets:
            currTarget.path = currTarget.determineOutputPath(options)
    else:
        cleaningOutputReported = False
        for currTarget in project.targets:
            if currTarget.outputPath != "" and os.path.exists(currTarget.outputPath):
                if cleaningOutputReported:
                    Logger().writeMessage("Cleaning MixDown and Target output directories...")
                    cleaningOutputReported = True
                utilityFunctions.removeDir(currTarget.outputPath)

        prefixDefine = options.getDefine(mdStrings.mdDefinePrefix)
        if prefixDefine != "":
            #TODO: only add lib64 if on 64bit machines
            libraryPaths = os.path.join(prefixDefine, "lib") + ":" + os.path.join(prefixDefine, "lib64")
            if os.environ.has_key("LD_LIBRARY_PATH"):
                originalLibraryPath = str.strip(os.environ["LD_LIBRARY_PATH"])
                if originalLibraryPath != "":
                    libraryPaths += ":" + originalLibraryPath
            os.environ["LD_LIBRARY_PATH"] = libraryPaths

    #Add MixDown's directory to path so mdSteps can be found
    sys.path.append(os.path.dirname(sys.argv[0]))

    return project

def cleanMixDown(options):
    try:
        Logger().writeMessage("Cleaning MixDown directories...")
        utilityFunctions.removeDir(options.buildDir)
        utilityFunctions.removeDir(options.downloadDir)
        utilityFunctions.removeDir(options.logDir)
    except IOError, e:
        Logger().writeError(e, exitProgram=True)

#----------------------------------------------------------------------

if __name__ == "__main__":
    main()
